### ISSUE TITLE
Hidguardian's AffectedDevices Deleted at Exit.

### ISSUE THREAD

**Issue by KiNGKiMO** [x360ce/x360ce#1174]
Hello,

As title stated, when exit x360ce now the "AffectedDevices" reg value gets cleared.

I've tested with version 4.14.9.0.

Thanks.

**Comment by EJocys** [comment]
This is done on purpose. Some inexperienced users did not know how to unhide devices. So, when x360ce is closed it cleans up after itself i.e. makes sure that all devices are made available to the system again. I can make clean-up an optional thing which could be disabled on Options tab. Or, maybe, I could "mark" AffectedDevices registry records created by x360ce, so that only those records would be wiped on close.

**Comment by KiNGKiMO** [comment]
Well, If one knows how to hide, they probably know how to unhide..
Also, devices do not get hidden immediately, they have to be re-attached if I recall.
An optional clean-up option would be great I guess though.

Thank you.

**Comment by EJocys** [comment]
Option to disable automatic HID Guardian configuration was added to [Options] Tab -> [Virtual Device] Tab.
