### ISSUE TITLE
Mac?

### ISSUE THREAD

**Issue by cjonasw** [x360ce/x360ce#124]
Any plans to make this compatible on Mac? Or is there a suitable alternative?

**Comment by Nucleoprotein** [comment]
As DirectInput and Xinput are Windows only APIs - nope.

**Comment by schumannd** [comment]
are there any alternatives for mac?

EDIT: What I ended up using as a workaround was [enjoyable](https://yukkurigames.com/enjoyable/)

**Comment by pkantsedalov** [comment]
@schumannd Hi!
Can you help me please? I have [Speedlink SL-6556-BK](https://www.speedlink.com/en/Gaming/PC-Gaming/Gamepads-oxid/wired/XEOX-PRO-ANALOG-GAMEPAD-USB-BLACK.html) and I can't adjust it to FIFA 12 on Mac in order to make it's right analog work and remap the buttons. Do you have any success with any other software?

**Comment by schumannd** [comment]
@pkantsedalov did you try enjoyable? It can pretty much configure every controller there is.

**Comment by pkantsedalov** [comment]
@schumannd Can you tell me please how to control exactly FIFA there?

**Comment by schumannd** [comment]
It is a program to map controller keys to keyboard keys and use the keyboard controls within FIFA. For the rest read the documentation.

**Comment by pkantsedalov** [comment]
@schumannd Thank you a lot, it works now!
