### ISSUE TITLE
Close program after exit game

### ISSUE THREAD

**Issue by Aditya354** [x360ce/x360ce#130]
I used latest ver(3.07.55) why stil close program after me exit game
all games, too http://i.imgur.com/6bADG08.jpg

while ver 2.0.2.160 beta not, why??

**Comment by Squall-Leonhart** [comment]
That is not a crash in our library, which suggests a bad controller driver or ffb library.

**Comment by Aditya354** [comment]
but why version 2.0.2.160 beta 2 does not?
http://i.imgur.com/0n3oPzT.jpg

**Comment by Omegasupremus** [comment]
That's exactly what's happening to me too. When I used the beta version 2.0.2.160, it worked perfectly, including Force Feedback (Left and Right). When I updated to version 3.7.55 in order to play Dark Souls 2 scholar of the first 64 bit version sin, only one side of the force feedback works in X360ce.exe Setup program.

And when I try to get out of any game that has been configured to use X360ce, the same problem occurs that Aditya354 described.

I do not think it's problems Drivers and FF, since they showed that work perfectly in older versions of X360Ce and other programs ...

**Comment by Squall-Leonhart** [comment]
what you think and what we know as reality are different.

We are using functions that behave properly on known good driver, but fail to release on known bad drivers.

**Comment by Nucleoprotein** [comment]
PR #143

**Comment by Garry050** [comment]
Error occurs when I am also the end of the game
It seems to occur mainly in the Steam game
For example, it is the case of Metal Gear Solid V Ground Zeroes

Problem Event Name: APPCRASH
Application Name: MgsGroundZeroes.exe
Application Version: 1.0.0.5
Application Timestamp: 5507e9dd
Fault Module Name: gameoverlayrenderer64.dll
Fault Module Version: 2.81.34.6
Fault Module Timestamp: 55708c4d
Exception Code: c0000005
Exception Offset: 00000000000e3d5e
OS Version: 6.3.9600.2.0.0.768.101
Locale ID: 1041
Additional Information 1: 7744
Additional Information 2: 7744ce83ff502a1d4eed6c2bc456f4c0
Additional Information 3: 0a65
Additional Information 4: 0a656918770911784b63f3369e7c357c

Even if it is not connected to the game pad , it is a problem that even if you disable the game over layer occur :(

Sorry my english

**Comment by Squall-Leonhart** [comment]
issues with steam have nothig to do with this bug.

**Comment by Garry050** [comment]
I have misread the meaning of the title.
sorry
