### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by hypertrophic15** [x360ce/x360ce#1301]
- 👋 Hi, I’m @hypertrophic15 im just wondering when i click to download it says that i have to pay and my friends doesn't get payment issues popping up so im confused why i do.

**Comment by EJocys** [comment]
Where are you getting this message? Could you provide the link? X360CE is completely free.

These are official links which will auto-redirect to release files on GitHub:

Version 4.x:
https://www.x360ce.com/files/x360ce.zip

Version 3.x:
https://www.x360ce.com/files/x360ce_x86.zip
https://www.x360ce.com/files/x360ce_x64.zip

Direct download links:
https://github.com/x360ce/x360ce/releases/download/4.17.0.0/x360ce.zip
https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce_x64.zip
https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce_x86.zip

**Comment by hypertrophic15** [comment]
it says my winzip trial has expired and i would need to buy it but i didn't even have winzip anyways. but it only says it when i click to open the file.

**Comment by EJocys** [comment]
Description suggest that issue is on your local PC. You either have WinZip or web/file browser have some weird extension. I avoid WinZip, because their brand was known for running Internet scams (WinZip System Tools). Windows have native support for ZIP archives, except when files encrypted with AES-256. Free and open source 7-Zip is much better alternative.
