### ISSUE TITLE
Why are you recommending against hiding the real device?

### ISSUE THREAD

**Issue by porg** [x360ce/x360ce#1343]
### After reading both the documentations of x360ce and ds4-windows
I assume that **HID-Guardian** for **x360ce** is essentially the same as **HidHide** is for **ds4-windows**.

A method to hide the real device and only show the emulated device among the  available OS input devices.

### What is strange to me is that the recommendations of x360ce and ds4-windows differ diametrically!

- DS4windows strongly recommends to hide the real device to avoid double input issues [^1]
  - To me this seems the plausible more compatible recommendation.
- whereas x360ce recommends to only install the real device hiding driver if having issues with games. [^2]
  - To me this seems more complex and error-prone.
  - What are your reasons for this recommendation?
  - Because to me the danger of locking yourself out of Windows by incidentally disabling mouse/keyboard seems to be neglible (you offer a fix instruction for this anyhow) in comparison to the many misconfigurations potentially resulting from double input (real + virtual), getting even more confusing when having 2 or more physical controllers connected.

[^1]: https://ds4-windows.com/get-started/
Important Steps to use DS4 correctly.
"Hiding" the real gamepads being used so only DS4Windows’ virtual controllers remain visible to games in order to prevent the infamous Double Controller or Double Input Issue.
This is THE major recommendation to be followed in order to prevent problems in games.

[^2]: https://github.com/x360ce/x360ce/wiki/HID-Guardian
Install HID Guardian only if original controller prevents virtual controller to function properly in the game.

**Comment by EJocys** [comment]
@porg: You are right. Not hiding real devices caused more issues with games. Locking yourself is negligible, but when it happens it stress some people a lot, because sometimes they will be locked out of extremely valuable things for them. I just feel guilty when it happens. Problems with the game is less serious than loosing access to PC and I agree with "what you do not wish for yourself, do not do to others" :). These were reasons why safer recommendation was made i.e. not to use HID Guardian if game works i.e. if it ain't broke, don't fix it. Proper solution would be to implement safer version of HID Guardian into X360CE. Last time, I've checked it exists, but lacked documentation.

As a safer alternative to HID Guardian, I would like to try and add an option for X360CE to acquire all real game controllers exclusively, so they won't be available for the game. It will be safer option, because everything will go back to normal when x360ce.exe closes.

P.S.: At the moment X360CE developing is slow, because I have other temporary pressing matters to resolve first.
