### ISSUE TITLE
Computer falls asleep

### ISSUE THREAD

**Issue by CeruleanSky** [x360ce/x360ce#141]
With xinput1_3.dll 64bit version 3.4.1.1324  the input from the controller does not prevent the computer from entering a lower power state.

I am testing with witcher 3 in borderless windowed mode and full screen mode.

Hook type: default

If you need any more additional info let me know.

Edit: Seems this problem isn't unique: https://steamcommunity.com/app/292030/discussions/0/617335934151681640/

**Comment by Squall-Leonhart** [comment]
problem is in the game itself, but there might be a change we can make that will set a windows api command to prevent this happening

**Comment by Nucleoprotein** [comment]
This is default design of Windows - when using DirectInput Windows will sleep because it's not awaken every time you press key. 

But I think it will be very easy to add a wake option to x360ce, for now you can use KrossX Insomnia from here http://tiny.cc/magicaltools (A stand alone version of Pokopom's "Prevent Screensaver" option).

DEVS:
We can use this code from KrossX Insomnia in x360ce: https://github.com/KrossX/Insomnia/blob/master/Insomnia/Insomnia.cpp#L147
It uses two methods of awaking system - fake mouse event, and SetThreadExecutionState

**Comment by Squall-Leonhart** [comment]
Its not just dinput tapcio,  Sleeping dogs does this even with native xinput controllers.

SetThreadExecutionState should be utilised in any fullscreen application that wants to keep the screen awake.

**Comment by CeruleanSky** [comment]
Thanks, I found [Caffeine](http://www.zhornsoftware.co.uk/caffeine/index.html#download) before the reply, it also is small and simple at a 14k download.  It keeps the computer awake by sending a periodic F15 keyup event, with the option of choosing shift or other keys.

 I did look at Insomnia. and it choose an alternate way ,[sending a null mouse move event as shown by these lines here](https://github.com/KrossX/Pokopom/blob/443b2b65818de438d83c532aac7204c1dc983180/Pokopom/Stuff_Windows.cpp#L21-L63)

I can't say which way be better and would be less likely to be captured and switch an app from gamepad to mouse/keyboard, though I'm sure for the majority of titles either would be fine, I can say for witcher3 keyup seems to work.

The reason I opened was that witcher 2(which I just finished) worked fine without ever sleeping, and both of course don't sleep when you have an official xbox controller, so I thought x360ce might be used in a different way for witcher 3.

Thank  you for considering adding support, and I'm sure there will be a lot of other people thankful also as in my google search for x360ce and standby/screensaver, there are a lot of people on the steam forums and elsewhere I found that have the same issues and are scratching their heads why a 360 controller works fine and x360ce seems to work in some games and not others.

**Comment by araujorm** [comment]
Hi. This is definitely not only a defect of the game, because on witcher 3 this problem never happens with the original xbox 360 controller nor with a ps3 controller when used with scarlett.crush (free) driver (be it usb or bluetooth connected).

It however is 100% reproducible on witcher 3 with x360ce 64 bit v3.0.7.55 (2015-06-08) and Libraries 3.4.1.1324 (2015-06-06) and a generic usb gamepad.

It's very annoying to have to change computer power settings before playing or (at least not so bad) to resort to running a 3rd party utility like the one mentioned above by CeruleanSky before starting. So please don't forget this problem.

**Comment by Nucleoprotein** [comment]
It seems in both cases you devices used xinput class drivers so the driver itself awakes system when input event occurs.

**Comment by Nucleoprotein** [comment]
Closed by PR #156

PS: Yes, one line of code ...
