### ISSUE TITLE
Can not change mapping for controllers in x360ce.ini

### ISSUE THREAD

**Issue by Trollgaard-Sr** [x360ce/x360ce#244]
Version: 3.2.8.76
Game: Mad Max 2015
Win7_x64

I have got the G27 to work like a charm, but I can not manage to get the 360 Wireless Controller to work at the same time.

In the tutorial it says to mark "Passthrough" and set the controller "above". I gather it means that the XInput device should be mapped to PAD1 in x360ce.ini.

[Mappings]
PAD1=IG_dc5e4af061ff11e58001444553540000
PAD2=IG_7c65aae0f58511e38001444553540000
PAD3=
PAD4=

Whatever I do, x360ce sets it back to the above mappings with G27 as controller 1. Is this a bug or do I have to change it somewhere else?

**Comment by EJocys** [comment]
You have to use "Map To" feature in order to force controllers into specific positions [1-4].
1. Run x360ce.exe
2. Select the [Controller #] tab page corresponding to X360 Wireless Controller.
3. Open the [Direct Input Device] tab page (visible when the controller is connected).
4. Set "Map To" drop down list value to: 1.
5. (optionally) Set "Map To" drop down list values (repeat steps 2. to 4.) for other controllers, if you have them, to: 2, 3 or 4.
6. Click [Save] button.
7. Close x360ce Application, run the game.

**Comment by SneakPlayz** [comment]
When ever I try to change the Device type it doesnt do anything like the joystick list doesnt show up so i cant change it to gamepad help me also its the new version
