### ISSUE TITLE
My controller works in emulator, but not in a game

### ISSUE THREAD

**Issue by kfm-zz** [x360ce/x360ce#334]
Lately I've bought Gioteck VX-3 controller. When I first time plugged it into pc everything was fine, games worked with my cotroller. But on the next day when I tried to play, they(games) saw only analog sticks and 'B' button as a 'Start' button. In x360ce app everything worked correct but games sucked at all. I didn't change any settings in x360ce of course, the only thing is that I played with my new controller on ps3 after I played on pc. I don't think ps3 changed something in controller settings but I don't know. And one more thing: x360ce app didn't worked perfect on the first day. App acted like I kept pressing left trigger. Of course I didn't. But this little issue doesn't matter, because controller worked perfect with games. It's complicated... hope you understand. Glad for any help and sorry for my bad english ;>

**Comment by Squall-Leonhart** [comment]
"App acted like I kept pressing left trigger."

You are using an old version of the app+dll that we no longer support

**Comment by kfm-zz** [comment]
Problem solved: The reason of issue was that I used app for 32 bit systems. Now I am using newest version of 64bit x360ce and everything works perfect :> Thanks

**Comment by hellwisp** [comment]
I have this issue in Dark Souls SotFS.
Tried both x64 and x32 versions though I know that x64 should be used. Also tried older versions and messed with the game settings. The buttons are working correctly in the emulator, but in-game they don't work as intended. There is the beep signaling that the emulator starts up.
Works on my desktop PC. Not on this laptop.

Edit: Works after upgrading from Win7 to Win10

**Comment by JimDirt** [comment]
I am having the same issue  , I just got MXGP2 today from Steam (it was on sale for $1.99) , I have MXGP2021 and MXGP3 the X360CE works for it sort of on MXGP2021 (by Sort Of I mean that I could only get some of the mapping to work , but I was at least able to get the basic Throttle,Clutch ,Brakes and steering to work so I can at least ride the bike good enough to play  , I am using a Microsoft Sidewinder 2 Joystick (not a Controller but a actual Joystick like the games should be played on PC)

I'm using a old version of Windows 10 because the Feature Updates screw everything up and I end up having to reformat and put it back where it was  , so I found a program that allowed me to Sut Off Windows Updates , so it only did the Defender Updates but no Windows Feature Updates which is great   , so I am using 21H2 

, but I couldn't get it to work with MXGP3, so I had to download (I actually downloaded about 7 Emulators but only 2 work) the WoJ Emulator and I got that to work with MXGP3  but it won't work on MXGP2 or MXGP2021 , so basically none of these Emulators work for every game  , and so far they only seem to work with 1 game , but at least I was able to map the basic functions so I could play  , however with this X360CE I loaded the .exe for my MXGP2 and nothing is where its supposed to be in the game itself , but it is in the Emulator , which makes no sense to me  , and I tried remapping in the game and none of the buttons except for Start and Back work  and I can turn the bike  , but the Throttle is the wrong key and I can't remap it , same goes for Front/Rear brakes and Clutch and Camera View  , basically both games are set exactly the same in the Emulator  , but only MXGP2021 works with it

Now its giving some weird issue after I closed the game  , when I click to use Emulator in the Emulator menu , now its making a Windows sound like I am going back a page or something is closing , it does it over and over till I uncheck Emulator on the left side , so I don't know if its conflicting with something or what  , I tried making a 2nd controller mapping and copying the first controller mapping to the 2nd , and that worked , however it was a pain to get it to let me set it up  , then it did the same thing with the noise after closing the game because I couldn't remap anything in the game , so I deleted that and just changed the .exe from the 2021 game to the 2 game  , and now its doing that noise sound  , so I had to close it completely  

I am really frustrated that these Emulators don't do what they are supposed to do , and even though they look when mapping like they are working correctly , when you get in the game nothing works at all or barely works the way it should  , like I said I am unable to map ANY keys in MXGP2 with this Emulator , but I was able to in MXGP3  , so I would have thought everything would work the same for both games  , even adding the .exe for MXGP2 so I just click on it for GAME: and it should work  , but it doesn't 

It shows the Sidewinder 2 in the Menu where its supposed to be , but it's like the game doesn't see my Joystick , even though I can steer with it and use the throttle , but its the wrong button (I use Trigger for Throttle)

Any Idea's ??/ ... Thanks ... Jim
