### ISSUE TITLE
Aiming L2 + Shooting R2 PS4 controller

### ISSUE THREAD

**Issue by memphisobrien** [x360ce/x360ce#433]
hi! Im playing serious sam 3 + 360ce+ds4 for my ps4 controller. I dont know what went wrong, but 3 days ago my configuration changed and now i cant hold aim L2 and shoot at the same time with r2. I rly dont know if its a 360ce problem or a ds4 problem. Somebody allreadyhad this problem? some ideas? If I hold L2 and I shoot, the "aim goes off".

**Comment by R3cK17** [comment]
I have this same issue! it is extremely annoying and i don't know if there is even a work around? Need to enable simultaneous use of HAxis and IHaxis! Can't even do a fully sik skid because can't sit brake -_-

So frustrated as this app fixes 100% of my deadspot issue, but then this is game breaking LOL

Can anyone suggest anything at all? I am using an original xbox360 wireless receiver, genuine 360 controller and my game example is GTAV.
you can see it by enabling Pass-Through then switching to the controller "General" tab and you can then use both triggers at the same time, but...well, pass-through disables everything the software does. Sad.

**Comment by Nucleoprotein** [comment]
Dunno about configuration of DS4, if both triggers in DirectInput use single axis then this is normal behavior and we can't do anything about it.

For original X360 gamepad you require to use passtrough mode to use both triggers at once, because orginal X360 gamepad in DirectInput mode uses single axis for both triggers and this software is usermode software - we can't do anything about that. If you want only to remap Xinput buttons use KrossX Durazno: https://github.com/KrossX/Durazno
