### ISSUE TITLE
not working on A.O.T wings of freedom 

### ISSUE THREAD

**Issue by FelixWan** [x360ce/x360ce#485]
dinput8.dll and xInput1_3.dll are used
checked when the game is started, the above files cannot be removed
which mean the dlls are already hooked in game.
but the keys mapping just not working, also the starting beep sound didn't appear.
----------------------- update 2016-09-10 --------------------------
case closed...
the patch 2.0 finally uses xinput, and everything is ok now.

**Comment by FelixWan** [comment]
I guess I have some idea on this...
this game seems to be using direct input only....
that's why the xinput doesn't work.
however.... it can't recognize all the keys on my controller...
so, problem still exists...

**Comment by jvook** [comment]
IDK man I tried a dinput only device and I get no response.  You sure it is not xinput?

**Comment by Tomomax** [comment]
I'm having the same problem using a ps2 controller. It works fine on any other game. **D:**

**Comment by jvook** [comment]
This game is using dinput not xinput, so x360ce is not going to help.  Try
connecting without it.

**Comment by FelixWan** [comment]
To:  jvook
Actually, I am not that sure about is it only using direct input. But the tests I have done brings me to this conclusion.
The largest hint would be this game only lock the dInput8.dll instead of all other xInput*.dll, However, I still have no idea how to deal with this

**Comment by jvook** [comment]
I am using a real 360 pad on it but it didn't work right so I had to use xinput plus to fix the controller's dead zones.  Anyway my point being that xinputplus has to inject a real 360 pad as direct input in order to work with this game.  Maybe that helps to figure out, maybe not.

As a wild shot, you could try this: https://sites.google.com/site/0dd14lab/xinput-plus/xinput_with_x360ce (use google translate.  site is in japanese but the program is in english)

Remember to set dinput mode in xinput plus, and may require setting triggers to half+/half- in advanced dinput options.

**Comment by FelixWan** [comment]
I just have a directinput controller, that's why I use x360ce....
but half of the buttons on that directinput controller were not detected in game....

**Comment by jvook** [comment]
Yeah the directions I sent you are for direct input controller to x360ce to
xinput plus, and xinput plus works with this game.  It will probably work
for you, but you'll have to try.  I mean, I know its stupid that this port is so broken and you would need to do something insane like this but if it works, it works.

**Comment by wassimdragon** [comment]
guys i found a solution
and it work for me 
 I hope this helps other people too:
1. Launch the game with gamepad plugged... let it crash
2. Go to Windows Event Viewer
3. Go to Applications
4. Look for the Error that corresponds to AOT.exe, it should be recent since we just launched the game
5. Identify the problem in the Error description. Mine said:
Faulting application name:  AoT.exe 
Faulting module name: EZFRD64.DLL
So EZFRD64.DLL is causing the crash. That file is located at: C:\Windows\USB_Vibration\ which is a folder that contains gamepad files.
So i searched for it in the windows folder then i deleted it
and the game works fine with the gamepad!
enjoy ;)

**Comment by Nucleoprotein** [comment]
Easier - disable force feedback ? EZFRD64.DLL is yours gamepad DirectInput Force Feedback driver...

**Comment by wassimdragon** [comment]
yes ! mabe it'll work if you disable it

**Comment by Snezko** [comment]
I have no clue what you guys are talking about (i'm a complete nub at this stuff) but for me when i run the game with x360ce it's the same as when i run it without it has no effect, now if anyone could tell me in more simple (dumbed down) way how to make it work i'd be super happy :)

**Comment by FelixWan** [comment]
I still can't make it worked.
I have tried XInput Plus, it did triggered x360ce.
However, it crashes right after the beep sound of start up appear with error on either dinput8.dll or xinput1_3.dll.
It worked when I run full test on XInput Plus, it crashes when I double check the config with x360ce.exe. Seems like the compatibility of XInput plus + x360ce is not good =3=

how stupid is this game that I need to first convert my direct input controller to 360 controller using x360ce then convert it back to direct input using xinput plus to make it work ~"~

**Comment by Snezko** [comment]
Well at this point i gave up on x360ce just ended up playing with weird fucked up buttons ingame with my select/start not even working, better then playing on keyboard i think

**Comment by Lonewolf22113** [comment]
`with my select/start not even working`
Actually while messing around with the controls settings I found out that **L3 and R3** are pause/select buttons

**Comment by Snezko** [comment]
Yeah i found that out too from the start, the problem is you can't remap SELECT/START or the left,right,up,down :/

**Comment by jvook** [comment]
If the analog is working and then it seems you need the old favorite
solution joy2key.  Remap dinput buttons to keyboard for all buttons and
leave analog sticks disabled.  Maybe that will work.

**Comment by Snezko** [comment]
I'm thinking might be more simple to just rob a store for a xbox controller and be done with it.... simple a better solution then anything here lol xD all jokes aside i can't be arsed with all this bypasses and shits, i like a simple solution where i plug something in and it works or i just simply remap some buttons and i got what i want, so i'll wait till they fix this issue or just keep dealing with it the way it is. thanks for the help

**Comment by FelixWan** [comment]
case closed...
the patch 2.0 finally uses xinput, and everything is ok now.
