### ISSUE TITLE
Server down. So, how to configure x360ce offline?

### ISSUE THREAD

**Issue by lunaparadox** [x360ce/x360ce#486]
I'm a tech noob. And I have no idea how to configure x360ce offline.

**Comment by joshheinrichs** [comment]
I think this is a good argument for providing releases through GitHub since people can't download x360ce at the moment.

**Comment by lunaparadox** [comment]
yeah, and it can't load data from server. I chose Phillip wireless controller and I'm lucky to get it work fine with a little manual remap, but no vibration. Mine is twin usb joystick.

**Comment by EJocys** [comment]
Restarted server. Should be fine now.

**Comment by coadr93** [comment]
I think it's down again :(

**Comment by EJocys** [comment]
@coadr93: Thank you. Updated and restarted server. Should be fine now.

**Comment by coadr93** [comment]
Thank you! Is there a donation page :)?

**Comment by coadr93** [comment]
Hey. Since the last update, I've been experiencing some issues.

First, for the old 64 and 32 bit versions, automatic configuration is messed up, especially the right stick (up and down are right and left and vice versa). Also they sometimes do not detect the exe in the folder.

The all files version has a stranger issue, where both my controllers are mirrored. I looked for a setting to change this but I didn't find anything. So I can't play with two controllers. It's strange, but sometimes it works (no mirroring). Also, the bindings are very messed up, I had to manually set. New games always messed up bindings, but I copy paste from old games.

Am I doing smth wrong? How do I stop the mirroring?

I have to mention that I am using PS2 controllers connected via USB.
