### ISSUE TITLE
Darskiders Warmastered edition

### ISSUE THREAD

**Issue by Woaaaaah** [x360ce/x360ce#534]
This new remastered edition of darksiders is not detected by the program, so I just copied the files from original darksiders folder. After it controller started working but unfortunately the game crashes after some 1 minute. Any chance it'll get fixed?

**Comment by Squall-Leonhart** [comment]
there is no reason for it to crash except for if your vibraation driver is faulty.

**Comment by ElektroStudios** [comment]
I don't understand why this BUG REPORT is closed, since the OP have total reason, x360ce works fine with DarkSiders original version but it doesn't seems to support DarkSiders: **Warmastered Edition**, or at least the proper configuration/mask is not listed in the game compatibility list... so the controller is not detected when in game.

This need to be checked and fixed, not closed. Come on, more than one year has been past since the Warmastered Edition released...
