### ISSUE TITLE
Binding a slider/axis to a button

### ISSUE THREAD

**Issue by napalm00** [x360ce/x360ce#56]
It seems that it's currently not possible to bind an axis (or slider) to a button. I'm using the T.Flight Hotas X and the Z value change is displayed correctly in the joystick's tab in x360ce (ranging from 65k to 0) but if I bind it to a button (say, the bumpers) it doesn't trigger the button when moving the axis.
Adding this feature would be a great thing for e.g. GTA 5, which currently has no support for flight sticks and the like.
I suppose you could add some sort of check for the Z value and activate the button accordingly, but I could be wrong of course.

**Comment by jbienz** [comment]
This issue was fixed with checkin number deaccd2. You can build from source or wait for the next binary release. The existing GUI can be used to create the mappings but you'll need to edit the config to change the deadzones. EJoycs is working on updating the GUI to configure these deadzones as part of Issue #64.
