### ISSUE TITLE
Use HTTPS only

### ISSUE THREAD

**Issue by C0rn3j** [x360ce/x360ce#649]
Certificates from Let's Encrypt are free. The site only allows HTTP as HTTPS is broken, it should only allow HTTPS and redirect HTTP to HTTPS.

I've discussed this with another project here few days ago, feel free to look into it for further information about this.

https://github.com/bedrocklinux/bedrocklinux-website/issues/21

**Comment by EJocys** [comment]
Looks like this post was meant for a different project.

**Comment by C0rn3j** [comment]
It wasn't, this site loads in HTTP. Is this not the project's site?

http://www.x360ce.com/

**Comment by EJocys** [comment]
Site is not using HTTPS, because website is not using any sensitive data or authorisation. New version of x360ce app will have optional login or anonymous ID to make sure that configuration can be easily moved via Internet from one PC to another, but that part is also encrypted (RSA and AES-256) by the app, so HTTPS is not required. EXE installer is digitally signed, so there is not need to worry that it comes from doggy website. But, I will install HTTPS certificate at some point, because, HTTPS is a little bit safer and more preferred option by some.

**Comment by C0rn3j** [comment]
> EXE installer is digitally signed, so there is not need to worry that it comes from doggy website.

Practically nobody looks at digital signatures of binaries.

>But, I will install HTTPS certificate at some point, because, HTTPS is a little bit safer and more preferred option by some.

Great to hear, it shouldn't take more than 20 minutes to set it all up if you know at least a bit about the stuff.

As I said, you can look at the linked issue for resources.

I'd keep this issue open if you plan to implement it.

**Comment by EJocys** [comment]
Now you can use https://www.x360ce.com

**Comment by C0rn3j** [comment]
Awesome! Now redirect HTTP traffic to HTTPS, fix the cipher issue and all will be great!

https://www.ssllabs.com/ssltest/analyze.html?d=x360ce.com

**Comment by EJocys** [comment]
Thanks for advice about RC4. Disabled. Site now gets "A" rating on SSL Labs. I will check HTTPS redirection later, because old app still points to HTTP. I will try to enable HTTPS on a new version of app. According to Internet, it will increase server traffic by 6-7% and CPU use by 1-2%, but I can live with that.

**Comment by C0rn3j** [comment]
With HTTPS you can use the HTTP2 protocol, I think it may cut down on the traffic and provide other benefits.
I see your server is already using it, so maybe the traffic increase won't be as much.
