### ISSUE TITLE
x360ce.exe doesn't recognize that the gamepad is connected

### ISSUE THREAD

**Issue by gcenta** [x360ce/x360ce#74]
Hi, I've always used x360ce 2.0.2.11 beta2 with many games without any problems, but with the last game I installed it didn't worked, so i downloaded the latest version from your github (both the 32 and 64 bit version) and even though it recognizes a gamepad it doesn't detect that the gamepad is connected (the little controller status square stays red) what can i do?

**Comment by Squall-Leonhart** [comment]
What game would this be?

Read the troubleshooting?

**Comment by gcenta** [comment]
The game is Murdered soul suspect

**Comment by Squall-Leonhart** [comment]
Review the troubleshooting steps at the bottom of the readme.

**Comment by gcenta** [comment]
I've tried everything written on the troubleshooting but still the light doesn't turn green with the newest version :(

**Comment by Squall-Leonhart** [comment]
Do you have the Visual Studio 2013 runtime installed?

**Comment by gcenta** [comment]
Yes i do

**Comment by Squall-Leonhart** [comment]
Please obtain teamviewer, and tell  me when a good time is to take a look at the issue.

**Comment by gcenta** [comment]
Ok I got it, if you have time we can do it now :)

**Comment by Squall-Leonhart** [comment]
ok, send the id and passcode, i'll delete them as soon as i have them.

**Comment by gcenta** [comment]
id:424 401 194 passcode:3853

**Comment by Squall-Leonhart** [comment]
Ejocy, can you remove these from the controller settings database

Profile with no buttons assigned.
144B9ABE
A45A70C3
3D1BFEFC
E037E25B
22F20C9F

Profiles with Passthrough enabled:
F93A66CC
14018148
E9F92BE7
B746A761

**Comment by EJocys** [comment]
Done

**Comment by EJocys** [comment]
Done properly now.

**Comment by Squall-Leonhart** [comment]
Thanks.

Original issue has been resolved, so closing this issue.

**Comment by Akfiz** [comment]
When I googled my problem it linked me here, although you solved your issue it doesn't say how you solved it so everyone googling it will be left in the dark. This is why I think, that in this case, necro is justifiable, it will help other people who also had this problem and are looking for the solution on google.

- Someone suggested to get x360ce on another PC, let him download his files there, and then copy it on the PC that you want to use the gamepad on inside the game's folder. It worked for him, didn't work for me. 

In my case, everything that would go wrong has went wrong so I think I have a fix for everything. Here is how I made x360ce work step by step, from the worst to smallest problems:

I) Grey Light -> Controller is connected, the PC sees the controller, x360ce doesn't see the controller.

1) Don't have the x360ce file inside "Program Files" as for some reason the program cannot create the xinput file there. This should be mentioned on x360ce's download page but it isn't.
2) Unplug the Gamepad and then start x360ce without the gamepad. This sounds 100% weird, but when I did this, it asked me to create xinput. When I started it with the gamepad connected, it didn't ask me to create the xinput.
I believe the problem with the grey light was that x360ce cannot create the required files if its inside "Program Files".
After I did all of that, the grey light turned to red.

II) Red Light -> x360ce sees the controller but something isn't right.

3) Go to Control Panel -> Devices and Printers -> Select your Gamepad and do a test. Move the axis a bit and press a few buttons.
4) Go back to x360ce and click on auto-assign. If auto-assign doesn't work, make sure key buttons like "start" are assigned.
After I did all of that, the red light turned green, but it still didn't work.

III) Green Light -> x360ce says it should work, but it doesn't work.

- I tried to get an older x360ce version that a lot of people said it works. It didn't work for me.

5) Copy all the files inside x360ce, for me they were: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll, inside the files of the game you want to play.
6) It will show you the grey light again, giving you the impression that it did not work, but the controller is actually working.

Extra: If you want to play more than 1 game with x360ce, since the download page doesn't mention this either. Copy and paste a x360ce.exe with the necessary files (for me it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside every game that you want to play. It has an option for multiple games inside it, but I'm not sure how that works or why is it even there if you need one x360ce.exe inside the folder of every game you want to play.

**Short Version:** It didn't work originally because x360ce cannot create the required files if its inside "Program Files", so you will have to move the x360ce in your own folder outside "Program Files", unplug the controller, start x360ce and let him create its own files right there. Plug the controller back in and now the grey light will turn red. Do the controller testing in Control Panel -> Devices and Printers and inside x360ce press auto-assign, if auto-assign doesn't work make sure that key buttons such as "start" are assigned. Now the red light will turn green. Close x360ce, copy and paste all the new files (for me, it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside the game's file that was inside "Program Files". It will show a grey light on the controller but it will actually work inside the game.
