### ISSUE TITLE
no stick dead zone set up ?

### ISSUE THREAD

**Issue by mcc001** [x360ce/x360ce#78]
Hello,
I was windering if there would be a way to set up a stick dead zone ? Indeed, the racing games I try to test with the x360ce need some dead zone config to the stick, as it is possible to do in "xpadder". Idon't use xpadder because but this emulator doesn't emulate the analog gradual function of the stick so when I turn the steering wheel, as soon it leaves the dead zone I had set up, it turns very strongly in a very short time.

Thanks

**Comment by Squall-Leonhart** [comment]
Adjust the X Axis Sensitivity on the left thumb tab.

We use the devices native dead zone, or that set by the application.

**Comment by EJocys** [comment]
You can also use [Controller N] Tab -> [Left Thumb] tab, [Click here to apply Preset] button.
It will offer you the choice to apply correct 100% Anti-Dead zone for left and right thumbs:

const int XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE = 7849;
const int XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE = 8689;

Optionally you can apply your own 1-2% dead zone on top which is useful in GTA V, because it allows to keep car straight and stops character from walking when shooting (wheel must be set in the middle)

**Comment by Nucleoprotein** [comment]
This is really poor for MS for such big default deadzones ... but my original XBOX 360 Gamepad have loose stick in center so I think they done this because of cheap analog sticks they used in their  devices...

**Comment by mcc001** [comment]
Thanks for your help, It works perfectly now !
About original xbox 360 gamepads, I don't know if they have loose stick but in the game "BLUR", whatever would be the wheel I've used with x360ce, there is a big dead zone. This x360ce is just perfect to solve the problem.
