### ISSUE TITLE
logitech F310 and mini ninjas

### ISSUE THREAD

**Issue by kylerts** [x360ce/x360ce#99]
hi you probably have already  address before but if you dont mind helping me if i can be helped but i have been trying different methods to get my logitech f310 to work with mini ninjas, tried renaming the xinputs along with adding the dinput8 file, not sure if im doing something wrong but if you can walk me through it i would appreciate it, cheers

**Comment by Squall-Leonhart** [comment]
press the save button on the games list to create the GDB entry in its correct location and mini ninja's will just work with xinput1_3

Oh, wow, uh... hmm, i haven't added this game to the gdb,  probably because i wa never able to get the correct executable name.

Adding
HookDI=1
HookName=1

to ini under [inputhook] will do.

**Comment by kylerts** [comment]
Ok so i added the HookDI=1 & HookName=1 but the game still dont recognize the gamepad.

**Comment by kylerts** [comment]
Ok so i got it to worked
